apiVersion: v1
kind: Pod # https://kubernetes.io/docs/concepts/workloads/pods/
apiVersion: v1
kind: Pod
metadata:
  name: "fortune-cookies"
  namespace: default
  labels:
    app: fortune-cookies
spec:
  containers:
  - name: fortune-cookies
    image: "fortune_cookies"
    imagePullPolicy: Never
    ports:
    - containerPort: 3000 
  restartPolicy: Always
---

